# Generated by Django 4.0.3 on 2022-04-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=50, verbose_name='Příjmení')),
                ('narozeni', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('obec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Obec')),
                ('ulice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ulice')),
                ('psc', models.IntegerField(blank=True, max_length=5, null=True, verbose_name='PSČ')),
                ('cp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Číslo popisné')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
            ],
        ),
    ]
