# Generated by Django 4.0.3 on 2022-04-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0003_album_song_umelec_delete_osoba_delete_ucinkujici'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, verbose_name='Název')),
            ],
        ),
        migrations.DeleteModel(
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='zanr',
            field=models.ManyToManyField(to='databaze.zanr'),
        ),
    ]
