# Generated by Django 4.0.3 on 2022-04-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0004_zanr_delete_album_song_zanr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='umelec',
            options={'verbose_name': ('Umelec',), 'verbose_name_plural': 'Umelci'},
        ),
        migrations.AlterModelOptions(
            name='zanr',
            options={'verbose_name': ('Zanr',), 'verbose_name_plural': 'Zanry'},
        ),
        migrations.AddField(
            model_name='song',
            name='umelec',
            field=models.ManyToManyField(to='databaze.umelec'),
        ),
    ]
