# Generated by Django 4.0.3 on 2022-04-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0005_alter_umelec_options_alter_zanr_options_song_umelec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umelec',
            name='datum_zalozeni',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Datum vzniku'),
        ),
    ]
