# Generated by Django 4.0.3 on 2022-04-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0006_alter_umelec_datum_zalozeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='umelec',
            field=models.ManyToManyField(null=True, to='databaze.umelec'),
        ),
        migrations.AlterField(
            model_name='song',
            name='zanr',
            field=models.ManyToManyField(null=True, to='databaze.zanr'),
        ),
    ]
