# Generated by Django 4.0.3 on 2022-04-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0007_alter_song_umelec_alter_song_zanr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='umelec',
            field=models.ManyToManyField(to='databaze.umelec'),
        ),
        migrations.AlterField(
            model_name='song',
            name='zanr',
            field=models.ManyToManyField(to='databaze.zanr'),
        ),
    ]
