# Generated by Django 4.0.3 on 2022-05-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0008_alter_song_umelec_alter_song_zanr'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='umelec',
            name='popis',
            field=models.TextField(blank=True, null=True, verbose_name='Popis'),
        ),
    ]
