# Generated by Django 4.0.3 on 2022-05-30 16:56

import databaze.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0009_song_text_umelec_popis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_album', models.CharField(max_length=100, verbose_name='Název')),
                ('datum_vydani', models.DateField(blank=True, null=True, verbose_name='Datum vydání')),
                ('obrazek', models.FileField(null=True, upload_to=databaze.models.attachment_path, verbose_name='Soubor')),
                ('umelec', models.ManyToManyField(to='databaze.umelec')),
                ('zanr', models.ManyToManyField(to='databaze.zanr')),
            ],
            options={
                'verbose_name': ('Album',),
                'verbose_name_plural': 'Alba',
            },
        ),
    ]
