# Generated by Django 4.0.3 on 2022-05-30 17:40

import databaze.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0010_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='obrazek',
        ),
        migrations.AlterField(
            model_name='umelec',
            name='datum_zalozeni',
            field=models.IntegerField(blank=True, null=True, verbose_name='Datum vzniku'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=databaze.models.attachment_path, verbose_name='File')),
                ('type', models.CharField(blank=True, choices=[('audio', 'Audio'), ('image', 'Image'), ('text', 'Text'), ('video', 'Video'), ('other', 'Other')], default='image', help_text='Select allowed attachment type', max_length=5, verbose_name='Attachment type')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaze.album')),
            ],
            options={
                'ordering': ['-last_update', 'type'],
            },
        ),
    ]
