# Generated by Django 4.0.3 on 2022-05-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0011_remove_album_obrazek_alter_umelec_datum_zalozeni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='databaze.album'),
        ),
    ]
