# Generated by Django 4.0.5 on 2022-06-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaze', '0013_rename_album_attachment_umelec_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='umelec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaze.umelec'),
        ),
    ]
